### ISSUE TITLE
You must enter the settings error

### ISSUE THREAD

**Issue by triksmelb** [luluhoc/home-cinema-toolkit#3]
After entering and saving settings successfully, navigating to search by rating and entering a rating i.e. 8 Im getting error "You must enter the settings". Selecting v3 option gives a Server Error and a search seems to occur but no results are returned.

Running HCT on Synology Docker.

thanks in advance
<img width="1198" alt="Screen Shot 2020-10-13 at 10 15 25 pm" src="https://user-images.githubusercontent.com/12489962/95854946-65949a00-0da3-11eb-90c2-1237ec42ec50.png">
<img width="1194" alt="Screen Shot 2020-10-13 at 10 16 10 pm" src="https://user-images.githubusercontent.com/12489962/95854958-69282100-0da3-11eb-99eb-a2f95bfd970d.png">

**Comment by luluhoc** [comment]
Hey, 

Thanks for letting me know about this BUG. It should be resolved now. The build is in progress in DOCKER, wait for it it should say updated today in a few minutes. Let me know if it works

**Comment by triksmelb** [comment]
thank you for your response.
Deleted old container and installed new container using:
```
docker run -d \
  --name HCT \
  -p 12400:12400 \
  --restart unless-stopped \
  lulu45/home-cinema-toolkit:latest
```
appears the same issue persists - settings are saved but a search by rating (8) gives error 
<img width="1287" alt="Screen Shot 2020-10-14 at 1 24 58 pm" src="https://user-images.githubusercontent.com/12489962/95936203-c7471980-0e20-11eb-844d-518b26b33f3b.png">

**Comment by triksmelb** [comment]
Upgraded Radarr to v3 and enabled v3 option in HTC. 

Now search works and all movies are found with correct rating. When I tick a movie and click delete I get the error again "You must enter the settings" 

HTC doesn't appear to delete the movie.

<img width="1440" alt="Screen Shot 2020-10-14 at 3 09 17 pm" src="https://user-images.githubusercontent.com/12489962/95942698-96221580-0e2f-11eb-81e8-a32faa4ecb4e.png">

**Comment by luluhoc** [comment]
Can you update the container and tell me on which version you are?

also, go to chrome console and SS me what it shows when you try to delete a movie.
![image](https://user-images.githubusercontent.com/22813220/95971496-9ad7d100-0e11-11eb-9583-d57f47b0655f.png)


![image](https://user-images.githubusercontent.com/22813220/95966794-d8396000-0e0b-11eb-9d33-47db10368a13.png)
