### ISSUE TITLE
Issue Deleting

### ISSUE THREAD

**Issue by msmcpeake** [luluhoc/home-cinema-toolkit#4]
![image](https://user-images.githubusercontent.com/54709869/96184048-e5d31080-0f05-11eb-9a16-5a56025bc055.png)

When the list finally populates and I select all movies and hit delete, I get this error.  

I am using Radarr v3

Sample log from Radarr:

```
2020-10-15 16:44:54.0|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/movie/3885

[v3.0.0.3716] System.FormatException: String 'undefined' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at Radarr.Http.Extensions.RequestExtensions.GetBooleanQueryParameter(Request request, String parameter, Boolean defaultValue) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 58
   at Radarr.Api.V3.Movies.MovieModule.DeleteMovie(Int32 id) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 193
   at Radarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 87
   at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

2020-10-15 16:44:54.0|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/movie/4276

[v3.0.0.3716] System.FormatException: String 'undefined' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at Radarr.Http.Extensions.RequestExtensions.GetBooleanQueryParameter(Request request, String parameter, Boolean defaultValue) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 58
   at Radarr.Api.V3.Movies.MovieModule.DeleteMovie(Int32 id) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 193
   at Radarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 87
   at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)

2020-10-15 16:44:54.0|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/movie/4278

[v3.0.0.3716] System.FormatException: String 'undefined' was not recognized as a valid Boolean.
   at System.Boolean.Parse(ReadOnlySpan`1 value)
   at System.Boolean.Parse(String value)
   at CallSite.Target(Closure , CallSite , Type , Object )
   at Radarr.Http.Extensions.RequestExtensions.GetBooleanQueryParameter(Request request, String parameter, Boolean defaultValue) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 58
   at Radarr.Api.V3.Movies.MovieModule.DeleteMovie(Int32 id) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 193
   at Radarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 87
   at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
```

Seems to only happen during a mass delete. I can delete single movies.

**Comment by luluhoc** [comment]
I know what it is I'm gonna fix it later

**Comment by luluhoc** [comment]
> ![image](https://user-images.githubusercontent.com/54709869/96184048-e5d31080-0f05-11eb-9a16-5a56025bc055.png)
> 
> When the list finally populates and I select all movies and hit delete, I get this error.
> 
> I am using Radarr v3
> 
> Sample log from Radarr:
> 
> ```
> 2020-10-15 16:44:54.0|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/movie/3885
> 
> [v3.0.0.3716] System.FormatException: String 'undefined' was not recognized as a valid Boolean.
>    at System.Boolean.Parse(ReadOnlySpan`1 value)
>    at System.Boolean.Parse(String value)
>    at CallSite.Target(Closure , CallSite , Type , Object )
>    at Radarr.Http.Extensions.RequestExtensions.GetBooleanQueryParameter(Request request, String parameter, Boolean defaultValue) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 58
>    at Radarr.Api.V3.Movies.MovieModule.DeleteMovie(Int32 id) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 193
>    at Radarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 87
>    at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)
>    at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
>    at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
>    at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
>    at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
>    at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
> 
> 2020-10-15 16:44:54.0|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/movie/4276
> 
> [v3.0.0.3716] System.FormatException: String 'undefined' was not recognized as a valid Boolean.
>    at System.Boolean.Parse(ReadOnlySpan`1 value)
>    at System.Boolean.Parse(String value)
>    at CallSite.Target(Closure , CallSite , Type , Object )
>    at Radarr.Http.Extensions.RequestExtensions.GetBooleanQueryParameter(Request request, String parameter, Boolean defaultValue) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 58
>    at Radarr.Api.V3.Movies.MovieModule.DeleteMovie(Int32 id) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 193
>    at Radarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 87
>    at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)
>    at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
>    at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
>    at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
>    at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
>    at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
> 
> 2020-10-15 16:44:54.0|Fatal|RadarrErrorPipeline|Request Failed. DELETE /api/v3/movie/4278
> 
> [v3.0.0.3716] System.FormatException: String 'undefined' was not recognized as a valid Boolean.
>    at System.Boolean.Parse(ReadOnlySpan`1 value)
>    at System.Boolean.Parse(String value)
>    at CallSite.Target(Closure , CallSite , Type , Object )
>    at Radarr.Http.Extensions.RequestExtensions.GetBooleanQueryParameter(Request request, String parameter, Boolean defaultValue) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 58
>    at Radarr.Api.V3.Movies.MovieModule.DeleteMovie(Int32 id) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieModule.cs:line 193
>    at Radarr.Http.REST.RestModule`1.<set_DeleteResource>b__27_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 87
>    at Nancy.NancyModule.<>c__DisplayClass8_0`1.<Delete>b__0(Object args)
>    at Nancy.NancyModule.<>c__DisplayClass10_0`1.<Delete>b__0(Object args, CancellationToken ct)
>    at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
>    at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
>    at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
>    at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)
> ```
> 
> Seems to only happen during a mass delete. I can delete single movies.

There was a typo in frontend :) it should work now. Please let me know if it works for you.

**Comment by luluhoc** [comment]
wait for docker to build the image and pull it :) you should be on 1.0.2 when the image is pulled.

**Comment by msmcpeake** [comment]
> wait for docker to build the image and pull it :) you should be on 1.0.2 when the image is pulled.

Hi, I am now on v1.0.2 and I still get this error on a mass delete.

**Comment by luluhoc** [comment]
> > wait for docker to build the image and pull it :) you should be on 1.0.2 when the image is pulled.
> 
> Hi, I am now on v1.0.2 and I still get this error on a mass delete.

Please try 1.0.3, I moved Delete movies and Add exclusions to settings.

**Comment by luluhoc** [comment]
Please let me know if it works for you :)

**Comment by msmcpeake** [comment]
> Please let me know if it works for you :)

Fixed :) Thanks so much!
