### ISSUE TITLE
IMDB vote sorting error

### ISSUE THREAD

**Issue by kjac3585** [luluhoc/home-cinema-toolkit#9]
Arranging search results by imdb votes gives erratic sorting, higher numbers mixed in with lower numbers etc...

**Comment by luluhoc** [comment]
this bug is resolved.

**Comment by kjac3585** [comment]
hmm, seems like it still exists in the updated version. I deleted the docker container and image and pulled a new image that says created (XX minutes ago) so it should be the latest version.

[https://i.imgur.com/0qeu7Mz.png](https://i.imgur.com/0qeu7Mz.png)

**Comment by luluhoc** [comment]
Docker Hub hasn't built yet the image

**Comment by luluhoc** [comment]
Please wait for a little bit

**Comment by luluhoc** [comment]
Pull a new image it is ready :)

**Comment by kjac3585** [comment]
got it, looks like it's almost 100% fixed, but one movie is out of place (Stargate), for some reason it has a comma in the numbers while none of the others do.

[https://i.imgur.com/ThCHt5d.png](https://i.imgur.com/ThCHt5d.png)

**Comment by kjac3585** [comment]
also, not sure if this would be an omdb/imdb issue or not, but I just happened to noticed one movie appears to have the wrong votes/rating. I looked to see if there was another movie with this name and I didn't see any. 

[If Anything Happens I Love You (2020)](https://www.imdb.com/title/tt11768948/)

[https://i.imgur.com/One9XQ0.png](https://i.imgur.com/One9XQ0.png)
